#ifndef STATSEM_H
#define STATSEM_H

#include <vector>
#include <fstream>

#include "tree.h"

/*
Static Semantics Definition
  * We impose rules on proper definition and use of variables
    + Variable definition
       - any identifier listed in any <varList> is definition of the variable named as the identifier instance
    + Variable use - identifier showing up in any statement (not under <varList>)
  * Static semantic rules
    + Variable can only be defined once in a scope, a second definition is an error, should be reported and the program exits
    + Variable must be defined before its first use, otherwise the variable is reported as an error and the program exits
    + A defined variable must be used, otherwise report a detailed warning and continue the program
*/



class SemanticTable 
{
  private:
    struct Row 
    {
      std::string varName;
      bool used;
      int line;
    };
    std::vector<Row> table; //The semantic table
    
    /*
     * Definition: Checks if the table has a given VARNAME.Saves its location in the table to location
     * Passed:     The VARNAME we are looking for and a integer location to save its location in the table
     * Returns:    True if found otherwise false
     */
    bool contains(const std::string VARNAME, int& location);
    
    
  public:
    /*
     * Definition: This function builds the semantic table. It traverses in preorder.
     *             Throws a invalid_argument if the variable is declare more than once or if a variable is used without declaration.
     * Passed:     The root of the parse tree
     */
    void buildSemanticTable(const std::unique_ptr<Node>& NODE);
    
    /*
     * Definition: Inserts a row into the semantic table
     * Passed:     Variable name and line number it was found on
     */
    void insert(const std::string VARNAME, const int LINE);
    
    //Definition: Prints warning if a variable has not been used by the program
    void printWarnings();
    
    //Prints the semantic table variable names follow by 0 to the given ofstream
    //EXP: x1 0
    void tableOut(std::ofstream& fileOut);
    
    SemanticTable();
};

/*
 * Definition: This function checks the static semantics of the given parse tree and generates a table of variables in the program.
 *             Scope is global. Redecleration of variables or using without being initialized is an error/
 *             The fucntion then prints warnings for variables declared but not used.
 * Passed:     The root of the parse tree generated by the parser for the language.            
 * Returns:    A pointer to the generated semantic table.
 */
std::unique_ptr<SemanticTable> buildTable(const std::unique_ptr<Node>& ROOT);





























/*
 * Definition: Current start of parse function.It builds a semantics table and checks for errors and warnings on variables.
 *             It will also catch any lexical errors and parse errors and display those.
 * Passed:     The filename of the input program

void staticSemantics(const std::string FILENAME);
*/

#endif